version: "3.2"

services:
  app:
    container_name: app
    image: dallanbhatti/course:test
    restart: on-failure
    env_file:
      - env/test/.env.app
    healthcheck:
      test: curl --fail -s app:5000/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db
    networks:
      - test-net
  db:
    container_name: db
    image: postgres:9.6
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - env/test/.env.db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - test-net
volumes:
  db_data:
networks:
  test-net:
    driver: bridge